# Plugin configuration for Spigot Updater
# Copy this file to plugins.yaml and customize for your setup

# Example SpigotMC plugin (commented out)
# Spartan:
#   source: 'spigot'  # spigot | github | jenkins | direct
#   # url: 'https://www.spigotmc.org/resources/spartan-advanced-anti-cheat-hack-blocker.25638/'
#   resource: 25638
#   jar: 'Spartan.jar'

BTLP_Bungee:
  source: 'spigot'
  # url: 'https://www.spigotmc.org/resources/bungeetablistplus.313/'
  resource: 313
  # zip_path: 'BungeeTabListPlus_Bungee.jar'  # exact name
  zip_path: 'BungeeTabListPlus-\S*\.jar'  # regex for versioned names
  jar: 'BTLP-Bungee.jar'

BTLP_Bukkit:
  source: 'spigot'
  # url: 'https://www.spigotmc.org/resources/bungeetablistplus.313/'
  resource: 313
  # zip_path: 'BungeeTabListPlus_BukkitBridge.jar'  # exact name
  zip_path: 'BungeeTabListPlus_BukkitBridge-\S*\.jar'  # regex for versioned names
  jar: 'BTLP-Bukkit.jar'

Companies:
  source: 'spigot'
  resource: 16712
  jar: 'Companies.jar'

Left4Chat:
  source: 'github'
  repo: 'left4craft/left4chat'  # renamed from 'repository'
  asset: 'Left4Chat.jar'
  jar: 'Left4Chat.jar'

EssentialsX:
  source: 'github'
  repo: 'essentialsx/essentials'  # renamed from 'repository'
  # asset: 'EssentialsX-\S*\.jar'  # regex for versioned names
  asset: 'EssentialsX-{{tag}}.0.jar'  # {{tag}} placeholder for github
  jar: 'EssentialsX.jar'

ProtocolLib:
  source: 'github'
  repo: 'dmulloy2/protocollib'  # renamed from 'repository'
  asset: 'ProtocolLib.jar'
  jar: 'ProtocolLib.jar'

FAWE:
  source: 'jenkins'
  host: 'https://ci.athion.net'
  job: 'FastAsyncWorldEdit-1.17'
  artifact: 'FastAsyncWorldEdit-1.17-{{build}}.jar'  # {{build}} placeholder for jenkins
  jar: 'FastAsyncWorldEdit.jar'
